server:
  servlet:
    context-path: /open.edit
  port: 8082
spring:
  data:
    mongodb:
      database: bolg
      host: localhost
      port: 27017
  thymeleaf:
    prefix:
      classpath: /templates   # 访问template下的html文件需要配置模板，映射
    cache: false # 开发时关闭缓存,不然没法看到实时页面
logging:
  pattern:
    console:%yellow(%date{yyyy-MM-dd HH:mm:ss}) |%highlight(%-5level) |%blue(%thread) |%blue(%file:%line) |%green(%logger) |%cyan(%msg%n)"

